spring:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled=true

  application:
    name: LastTest

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Nmjt1915!@
#mybatis:
#  type-aliases-package: com.example.lasttest.model
#  mapper-locations: classpath*:/mapper/**/*.xml
